### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by yash2189** [yash2189/Clima-Flutter#1]
# Create a proper Contributing File

This a beginner friendly documentation  issue.

- [ ] Create a proper `CONTRIBUTING.md` file. Describe as much you can.
- [ ] Update `README.md`
- [ ] Follow a proper commit style guideline. ( Eg: `doc: your message here` )
- [ ] Please describe your work done in the PR.

**Comment by Kunal1198** [comment]
Hi @yash2189 Can I work on this?

**Comment by yash2189** [comment]
Yes sure @Kunal1198

**Comment by Kunal1198** [comment]
Please review my PR #2 .
